### ISSUE TITLE
setup config incorreto

### ISSUE THREAD

**Issue by reinaldonunes** [Dhi-Carvalho-DEV/Ecoleta_Starter#1]
Olá amigo, o seus códigos de configuração do setup parecem estar incorretos ou faltando algo. Clonei o projeto, baixei as dependências, mas na hora de rodar, ele não ativa o servidor na porta 3000.. simplesmente o projeto não roda.

Poderia verificar se faltou alguma configruação no seu readme?

**Comment by Dhi-Carvalho-DEV** [comment]
Olá amigo, acabei de corrigir...

**Comment by reinaldonunes** [comment]
show, vou verificar
